"""baseline_schema

Revision ID: 35c5c17fcff7
Revises: 
Create Date: 2026-03-31 19:29:13.512774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35c5c17fcff7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('mall_name', sa.String(length=120), nullable=False),
    sa.Column('data_origin', sa.Enum('DEMO', 'LIVE', name='merchantdataorigin', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mall_name')
    )
    op.create_index(op.f('ix_merchants_data_origin'), 'merchants', ['data_origin'], unique=False)
    op.create_index(op.f('ix_merchants_id'), 'merchants', ['id'], unique=False)
    op.create_table('background_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('queue_name', sa.String(length=64), nullable=False),
    sa.Column('job_type', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'RETRY_SCHEDULED', 'SUCCEEDED', 'DEAD_LETTER', name='backgroundjobstatus', native_enum=False), nullable=False),
    sa.Column('triggered_by', sa.String(length=255), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_background_jobs_available_at'), 'background_jobs', ['available_at'], unique=False)
    op.create_index(op.f('ix_background_jobs_created_at'), 'background_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_background_jobs_id'), 'background_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_background_jobs_job_type'), 'background_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_background_jobs_merchant_id'), 'background_jobs', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_background_jobs_queue_name'), 'background_jobs', ['queue_name'], unique=False)
    op.create_index(op.f('ix_background_jobs_status'), 'background_jobs', ['status'], unique=False)
    op.create_table('cafe24_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('mall_id', sa.String(length=120), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_type', sa.String(length=32), nullable=False),
    sa.Column('scopes_json', sa.JSON(), nullable=True),
    sa.Column('access_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refresh_token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_token_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_result', sa.String(length=64), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_batch_id', sa.String(length=120), nullable=True),
    sa.Column('synced_orders', sa.Integer(), nullable=False),
    sa.Column('synced_claims', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cafe24_connections_id'), 'cafe24_connections', ['id'], unique=False)
    op.create_index(op.f('ix_cafe24_connections_mall_id'), 'cafe24_connections', ['mall_id'], unique=False)
    op.create_index(op.f('ix_cafe24_connections_merchant_id'), 'cafe24_connections', ['merchant_id'], unique=True)
    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=64), nullable=False),
    sa.Column('customer_name', sa.String(length=120), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('DELIVERY', 'CANCELLATION', 'EXCHANGE', 'RETURN', 'REFUND', 'DEFECT', 'MISDELIVERY', 'OTHER', name='claimcategory', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_REVIEW', 'APPROVED', 'REJECTED', 'DONE', name='claimstatus', native_enum=False), nullable=False),
    sa.Column('reason_text', sa.Text(), nullable=False),
    sa.Column('ai_label', sa.String(length=120), nullable=True),
    sa.Column('urgency', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='claimurgency', native_enum=False), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.Column('delete_reason', sa.Text(), nullable=True),
    sa.Column('retention_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_deleted_at'), 'claims', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_claims_id'), 'claims', ['id'], unique=False)
    op.create_index(op.f('ix_claims_merchant_id'), 'claims', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_claims_order_no'), 'claims', ['order_no'], unique=False)
    op.create_index(op.f('ix_claims_retention_until'), 'claims', ['retention_until'], unique=False)
    op.create_table('operator_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('MANAGER', 'AGENT', 'VIEWER', name='operatorrole', native_enum=False), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operator_users_email'), 'operator_users', ['email'], unique=True)
    op.create_index(op.f('ix_operator_users_id'), 'operator_users', ['id'], unique=False)
    op.create_index(op.f('ix_operator_users_merchant_id'), 'operator_users', ['merchant_id'], unique=False)
    op.create_table('policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('exchange_window_days', sa.Integer(), nullable=False),
    sa.Column('return_window_days', sa.Integer(), nullable=False),
    sa.Column('return_shipping_fee', sa.Integer(), nullable=False),
    sa.Column('exchange_shipping_fee', sa.Integer(), nullable=False),
    sa.Column('refund_rule_text', sa.Text(), nullable=False),
    sa.Column('exception_rule_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id')
    )
    op.create_index(op.f('ix_policies_id'), 'policies', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_claim_id'), 'audit_logs', ['claim_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('cafe24_integration_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('batch_id', sa.String(length=120), nullable=True),
    sa.Column('claim_id', sa.Integer(), nullable=True),
    sa.Column('order_no', sa.String(length=120), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['cafe24_connections.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cafe24_integration_events_batch_id'), 'cafe24_integration_events', ['batch_id'], unique=False)
    op.create_index(op.f('ix_cafe24_integration_events_claim_id'), 'cafe24_integration_events', ['claim_id'], unique=False)
    op.create_index(op.f('ix_cafe24_integration_events_connection_id'), 'cafe24_integration_events', ['connection_id'], unique=False)
    op.create_index(op.f('ix_cafe24_integration_events_event_type'), 'cafe24_integration_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_cafe24_integration_events_id'), 'cafe24_integration_events', ['id'], unique=False)
    op.create_index(op.f('ix_cafe24_integration_events_merchant_id'), 'cafe24_integration_events', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_cafe24_integration_events_occurred_at'), 'cafe24_integration_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_cafe24_integration_events_order_no'), 'cafe24_integration_events', ['order_no'], unique=False)
    op.create_index(op.f('ix_cafe24_integration_events_status'), 'cafe24_integration_events', ['status'], unique=False)
    op.create_table('cafe24_webhook_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('merchant_id', sa.Integer(), nullable=False),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=255), nullable=False),
    sa.Column('external_event_id', sa.String(length=255), nullable=True),
    sa.Column('event_type', sa.String(length=120), nullable=False),
    sa.Column('signature', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('failed_reason', sa.Text(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['cafe24_connections.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cafe24_webhook_deliveries_connection_id'), 'cafe24_webhook_deliveries', ['connection_id'], unique=False)
    op.create_index(op.f('ix_cafe24_webhook_deliveries_dedupe_key'), 'cafe24_webhook_deliveries', ['dedupe_key'], unique=True)
    op.create_index(op.f('ix_cafe24_webhook_deliveries_event_type'), 'cafe24_webhook_deliveries', ['event_type'], unique=False)
    op.create_index(op.f('ix_cafe24_webhook_deliveries_external_event_id'), 'cafe24_webhook_deliveries', ['external_event_id'], unique=False)
    op.create_index(op.f('ix_cafe24_webhook_deliveries_id'), 'cafe24_webhook_deliveries', ['id'], unique=False)
    op.create_index(op.f('ix_cafe24_webhook_deliveries_merchant_id'), 'cafe24_webhook_deliveries', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_cafe24_webhook_deliveries_received_at'), 'cafe24_webhook_deliveries', ['received_at'], unique=False)
    op.create_index(op.f('ix_cafe24_webhook_deliveries_status'), 'cafe24_webhook_deliveries', ['status'], unique=False)
    op.create_table('claim_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_messages_claim_id'), 'claim_messages', ['claim_id'], unique=False)
    op.create_index(op.f('ix_claim_messages_id'), 'claim_messages', ['id'], unique=False)
    op.create_table('reply_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('MANUAL_HANDOFF', 'WEBHOOK', name='replydeliverychannel', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'FAILED', name='replydeliverystatus', native_enum=False), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=True),
    sa.Column('reply_body', sa.Text(), nullable=False),
    sa.Column('external_delivery_id', sa.String(length=255), nullable=True),
    sa.Column('request_payload_json', sa.JSON(), nullable=True),
    sa.Column('response_payload_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reply_deliveries_claim_id'), 'reply_deliveries', ['claim_id'], unique=False)
    op.create_index(op.f('ix_reply_deliveries_external_delivery_id'), 'reply_deliveries', ['external_delivery_id'], unique=False)
    op.create_index(op.f('ix_reply_deliveries_id'), 'reply_deliveries', ['id'], unique=False)
    op.create_table('suggested_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('draft_reply', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suggested_actions_claim_id'), 'suggested_actions', ['claim_id'], unique=False)
    op.create_index(op.f('ix_suggested_actions_id'), 'suggested_actions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_suggested_actions_id'), table_name='suggested_actions')
    op.drop_index(op.f('ix_suggested_actions_claim_id'), table_name='suggested_actions')
    op.drop_table('suggested_actions')
    op.drop_index(op.f('ix_reply_deliveries_id'), table_name='reply_deliveries')
    op.drop_index(op.f('ix_reply_deliveries_external_delivery_id'), table_name='reply_deliveries')
    op.drop_index(op.f('ix_reply_deliveries_claim_id'), table_name='reply_deliveries')
    op.drop_table('reply_deliveries')
    op.drop_index(op.f('ix_claim_messages_id'), table_name='claim_messages')
    op.drop_index(op.f('ix_claim_messages_claim_id'), table_name='claim_messages')
    op.drop_table('claim_messages')
    op.drop_index(op.f('ix_cafe24_webhook_deliveries_status'), table_name='cafe24_webhook_deliveries')
    op.drop_index(op.f('ix_cafe24_webhook_deliveries_received_at'), table_name='cafe24_webhook_deliveries')
    op.drop_index(op.f('ix_cafe24_webhook_deliveries_merchant_id'), table_name='cafe24_webhook_deliveries')
    op.drop_index(op.f('ix_cafe24_webhook_deliveries_id'), table_name='cafe24_webhook_deliveries')
    op.drop_index(op.f('ix_cafe24_webhook_deliveries_external_event_id'), table_name='cafe24_webhook_deliveries')
    op.drop_index(op.f('ix_cafe24_webhook_deliveries_event_type'), table_name='cafe24_webhook_deliveries')
    op.drop_index(op.f('ix_cafe24_webhook_deliveries_dedupe_key'), table_name='cafe24_webhook_deliveries')
    op.drop_index(op.f('ix_cafe24_webhook_deliveries_connection_id'), table_name='cafe24_webhook_deliveries')
    op.drop_table('cafe24_webhook_deliveries')
    op.drop_index(op.f('ix_cafe24_integration_events_status'), table_name='cafe24_integration_events')
    op.drop_index(op.f('ix_cafe24_integration_events_order_no'), table_name='cafe24_integration_events')
    op.drop_index(op.f('ix_cafe24_integration_events_occurred_at'), table_name='cafe24_integration_events')
    op.drop_index(op.f('ix_cafe24_integration_events_merchant_id'), table_name='cafe24_integration_events')
    op.drop_index(op.f('ix_cafe24_integration_events_id'), table_name='cafe24_integration_events')
    op.drop_index(op.f('ix_cafe24_integration_events_event_type'), table_name='cafe24_integration_events')
    op.drop_index(op.f('ix_cafe24_integration_events_connection_id'), table_name='cafe24_integration_events')
    op.drop_index(op.f('ix_cafe24_integration_events_claim_id'), table_name='cafe24_integration_events')
    op.drop_index(op.f('ix_cafe24_integration_events_batch_id'), table_name='cafe24_integration_events')
    op.drop_table('cafe24_integration_events')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_claim_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_policies_id'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_operator_users_merchant_id'), table_name='operator_users')
    op.drop_index(op.f('ix_operator_users_id'), table_name='operator_users')
    op.drop_index(op.f('ix_operator_users_email'), table_name='operator_users')
    op.drop_table('operator_users')
    op.drop_index(op.f('ix_claims_retention_until'), table_name='claims')
    op.drop_index(op.f('ix_claims_order_no'), table_name='claims')
    op.drop_index(op.f('ix_claims_merchant_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_deleted_at'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_cafe24_connections_merchant_id'), table_name='cafe24_connections')
    op.drop_index(op.f('ix_cafe24_connections_mall_id'), table_name='cafe24_connections')
    op.drop_index(op.f('ix_cafe24_connections_id'), table_name='cafe24_connections')
    op.drop_table('cafe24_connections')
    op.drop_index(op.f('ix_background_jobs_status'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_queue_name'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_merchant_id'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_job_type'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_id'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_created_at'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_available_at'), table_name='background_jobs')
    op.drop_table('background_jobs')
    op.drop_index(op.f('ix_merchants_id'), table_name='merchants')
    op.drop_index(op.f('ix_merchants_data_origin'), table_name='merchants')
    op.drop_table('merchants')
    # ### end Alembic commands ###
